### ISSUE TITLE
Confirmation on NASim scenario parameters used in the paper

### ISSUE THREAD

**Issue by Tudyx** [yyzpiero/RL4RedTeam#1]
I recently read your [great paper](https://arxiv.org/abs/2202.10630) about Clap algorithm and I would know if it's possible to have the [NASim](https://github.com/Jjschwartz/NetworkAttackSimulator) scenario to reproduce the result and compare with our algorithm.

You mention those parameters in the paper :

_ | Subnets | Hosts | OS | Services  | Processes
-|-|-|-|-|-
Small | 7 | 8 | 2 | 3 | 2
Medium | 6 | 16 | 2 | 5 | 3
Large | 8 | 23 | 3 | 7 | 3

I've remarked that the parameters seem to match ones defined in [NASim benchmarks](https://networkattacksimulator.readthedocs.io/en/latest/reference/scenarios/benchmark_scenarios.html).

So I suppose the scenario used in the paper corresponds to the following in NASim benchmarks :

Clap | NASim
-|-
Small | small-linear
Medium | medium
Large | large-gen

Am I right?

**Comment by yyzpiero** [comment]
Hi @Tudyx, you're absolutely right.  The scenario used in the paper is form the `NASim` benchmarks `small-linear`, `medium` and `large-gen` respectively. Anyways, I am currently working on scaling up the network size in our paper and addressing the Partial Observable problem. With all authors' consent, we plan to update the paper on arxiv.

**Comment by Tudyx** [comment]
Thanks! I look forward to the updated paper
